apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: production
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: "worker:prod"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "kidk/certification-images-api:latest"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 31000
    protocol: TCP
  selector:
    app: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached-default
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached-default
    spec:
      containers:
      - name: memcached-default
        image: "memcached:1.5.1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached-test
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached-test
    spec:
      containers:
      - name: memcached-test
        image: "custom-memcached:1.5.1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached-prod
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached-prod
    spec:
      containers:
      - name: memcached-prod
        image: "memcached-prod:prod"
